### ISSUE TITLE
Cannot specify a checkstyle filter file

### ISSUE THREAD

**Issue by DanielYWoo** [jenkinsci/checkstyle-plugin#7]
Often we have some generated thrift or google protocol buffers stubs, I can filter them in Maven or ANT, but the jenkins plugin always shows all the warnings. Hopefully there is a way to specify a filter file with this plugin

**Comment by uhafner** [comment]
The plug-in shows the maven results. So if you set the filter in your maven config, then the correct results are shown in the plugin.

BTW: please use http://issues.jenkins-ci.org/ when creating issues.
